### ISSUE TITLE
GIS Issue with JDK10

### ISSUE THREAD

**Issue by brettbelcher** [Repast/repast.simphony#15]
When running Repast Simphony with JDK10 and using the GIS library we get the following error:

```java
ERROR [AWT-EventQueue-0] 14:52:59,175 repast.simphony.ui.RSApplication - Error while initializing simulation
java.lang.IllegalArgumentException: org.geotools.styling.StyleFactory is not an ImageIO SPI class
	at java.desktop/javax.imageio.spi.ServiceRegistry.checkClassAllowed(Unknown Source)
	at java.desktop/javax.imageio.spi.ServiceRegistry.<init>(Unknown Source)
	at org.geotools.factory.FactoryRegistry.<init>(FactoryRegistry.java:155)
	at org.geotools.factory.FactoryCreator.<init>(FactoryCreator.java:91)
	at org.geotools.factory.CommonFactoryFinder.getServiceRegistry(CommonFactoryFinder.java:76)
	at org.geotools.factory.CommonFactoryFinder.lookup(CommonFactoryFinder.java:346)
	at org.geotools.factory.CommonFactoryFinder.getFilterFactory(CommonFactoryFinder.java:300)
	at org.geotools.factory.CommonFactoryFinder.getFilterFactory(CommonFactoryFinder.java:317)
	at org.geotools.data.store.ContentDataStore.<init>(ContentDataStore.java:173)
	at org.geotools.data.shapefile.ShapefileDataStore.<init>(ShapefileDataStore.java:124)
	at zikaVectorControl.ContextCreator.loadFeaturesFromFile(ContextCreator.java:205)
```
This is the code that throws the error
```java
import org.geotools.data.shapefile.ShapefileDataStore;
import org.geotools.data.simple.SimpleFeatureIterator;
import org.opengis.feature.simple.SimpleFeature;

Grid<Object> grid = (Grid<Object>) context.getProjection("Grid");
		URL url = null;
		try {
			url = new File(filename).toURL();
		} catch (MalformedURLException e1) {
			e1.printStackTrace();
		}
ShapefileDataStore store = null;
		store = new ShapefileDataStore(url);
```

**Comment by etatara** [comment]
Repast 2.5 requires Java 8 and may not work with Java 9/10.  We are currently working on the next release which will be compatible with Java 9/10/11.  The issue you report is due to a problem with the GeoTools library version 18.0 included with Repast that is not compatible with Java 9+.  The current "Java10_Development" branch of Repast on github includes Geotools 19.1 which is compatible with Java 10/11, however it's a bit complicated to build this for typical use.  In the meantime, please use Java 8 until we are able to release a version of Repast compatible with Java 10.

**Comment by etatara** [comment]
Repast 2.6 solves this issue.
