### ISSUE TITLE
errorous cast of double to int in FPRangeParameterBinder.

### ISSUE THREAD

**Issue by MelchiorUU** [Repast/repast.simphony#29]
In the FPRangeParameterBinder on line 64, in the resetToDefault() function, the code tries to cast a double to an int, where a double is required:

  public void resetToDefault() {
    Object defaultValue = params.getSchema().getDetails(getName()).getDefaultValue();
    **int val = ((Integer) defaultValue).intValue();**
    spinner.setValue(val);
  }

This line should be:

  double val = ((Number) defaultValue).doubleValue();

Context: the spinner is only use for double values. As such, the default value should always be a double. If your default value != a whole number you will get the following error:

Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: class java.lang.Double cannot be cast to class java.lang.Integer (java.lang.Double and java.lang.Integer are in module java.base of loader 'bootstrap')
	at repast.simphony.ui.parameters.FPRangeParameterBinder.resetToDefault(FPRangeParameterBinder.java:64)
	at repast.simphony.ui.parameters.ParametersUI.resetParameters(ParametersUI.java:195)
	at repast.simphony.ui.GUIParametersManager.reset(GUIParametersManager.java:56)
	at repast.simphony.ui.GUIParametersManager.reset(GUIParametersManager.java:79)
	at repast.simphony.ui.RSApplication.reset(RSApplication.java:450)
	at repast.simphony.ui.action.ResetRun.actionPerformed(ResetRun.java:17)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by ncollier** [comment]
Looks like a bug. SpinnerNumberModel can support all the number types. We should check if we had some reason for assuming integer -- probably just an oversight though.

**Comment by MelchiorUU** [comment]
If it supports all it would be interesting to look into the logic of selecting the visualization. 
Currently:
if (range = defined && type = int) -> slider
if (range = defined && type = double) -> spinner

If you also want to have a spinner for int values some other logic seems to be needed. Workaround is to use a double and only allow natural numbers by having a [N N N] range definition (instead of things like [N N R] with real numbers).

**Comment by ncollier** [comment]
Fixed in 3d94293b
