### ISSUE TITLE
GLProfiles 2 error with Ubuntu 20.04

### ISSUE THREAD

**Issue by ncollier** [Repast/repast.simphony#39]
User reports this stack trace with RS2.7 and Ubuntu 20.04

```
ERROR [AWT-EventQueue-1] 13:41:53,941 repast.simphony.visualizationOGL2D.DisplayOGL2D - Error initializing OGL 2D display. JOGL must be installed and computer must support open gl rendering
javax.media.opengl.GLException: Profile GL2 is not available on null, but: [GLProfile[GLES1/GLES1.hw], GLProfile[GLES2/GLES3.hw], GLProfile[GL2ES1/GLES1.hw], GLProfile[GL4ES3/GL4.hw], GLProfile[GL2ES2/GL4.hw], GLProfile[GL4/GL4.hw], GLProfile[GLES3/GLES3.hw], GLProfile[GL4/GL4.hw], GLProfile[GL3/GL4.hw], GLProfile[GL2GL3/GL4.hw]]
	at javax.media.opengl.GLProfile.get(GLProfile.java:962)
	at javax.media.opengl.GLProfile.get(GLProfile.java:975)
	at saf.v3d.Canvas2D.<init>(Canvas2D.java:82)
```

So it looks GL2 is not available, although others are.

**Comment by ncollier** [comment]
User resolved this with:

we actually found a way for it to work, but it's not that pretty:
When I go to the folder where the eclipse executable is in:

leonm@Leons-ThinkPad-T450:~/eclipse-committers-2019-06-R-linux-gtk-x86_64/eclipse$

and start eclipse via this commmand:

MESA_GL_VERSION_OVERRIDE=3.0 ./eclipse

it works!!!!



The command forces eclipse to run with OpenGL version 3.0.
When I try to run eclipse with OpenGL version 2.8:
MESA_GL_VERSION_OVERRIDE=2.8 ./eclipse
Or 2.9:
MESA_GL_VERSION_OVERRIDE=2.9 ./eclipse

instead I get the Grid and Space displays in the Repast window, but there are empty.


I also tried newer versions of OpenGL like 3.1, 3.2, 3.3, 4.0 and 3.3 Compatibility mode:
MESA_GL_VERSION_OVERRIDE=3.1 ./eclipse
MESA_GL_VERSION_OVERRIDE=3.2 ./eclipse
MESA_GL_VERSION_OVERRIDE=3.3 ./eclipse
MESA_GL_VERSION_OVERRIDE=4.0 ./eclipse
MESA_GL_VERSION_OVERRIDE=3.3COMP ./eclipse

but all of those reproduce the problem of not getting the displays at all.

After searching for solutions today we found out that the problem seems to be with either the graphics drivers or my graphics card or the combination of my laptop(and graphics card) with ubuntu.

In case this problem appears again here are my informations (created with inxi -Fz in linux terminal):

System:
 Kernel: 5.4.0-51-generic x86_64 bits: 64 Desktop: Gnome 3.36.4
 Distro: Ubuntu 20.04.1 LTS (Focal Fossa)
Machine:
 Type: Laptop System: LENOVO product: 20BUS4EW00 v: ThinkPad T450
 serial: <filter>
 Mobo: LENOVO model: 20BUS4EW00 v: SDK0E50510 WIN serial: <filter>
 UEFI: LENOVO v: JBET73WW (1.37 ) date: 08/14/2019
Battery:
 ID-1: BAT0 charge: 12.4 Wh condition: 16.6/23.2 Wh (72%)
 ID-2: BAT1 charge: 0.3 Wh condition: 3.9/23.5 Wh (17%)
CPU:
 Topology: Dual Core model: Intel Core i7-5600U bits: 64 type: MT MCP
 L2 cache: 4096 KiB
 Speed: 1157 MHz min/max: 500/3200 MHz Core speeds (MHz): 1: 922 2: 913
 3: 891 4: 929
Graphics:
 Device-1: Intel HD Graphics 5500 driver: i915 v: kernel
 Display: x11 server: X.Org 1.20.8 driver: i915 resolution: 1600x900~60Hz
 OpenGL: renderer: Mesa Intel HD Graphics 5500 (BDW GT2)
 v: 4.6 Mesa 20.3.0-devel (git-7758664 2020-10-14 focal-oibaf-ppa)
Audio:
 Device-1: Intel Broadwell-U Audio driver: snd_hda_intel
 Device-2: Intel Wildcat Point-LP High Definition Audio
 driver: snd_hda_intel
 Sound Server: ALSA v: k5.4.0-51-generic
Network:
 Device-1: Intel Ethernet I218-LM driver: e1000e
 IF: enp0s25 state: down mac: <filter>
 Device-2: Intel Wireless 7265 driver: iwlwifi
 IF: wlp3s0 state: up mac: <filter>
Drives:
 Local Storage: total: 238.47 GiB used: 26.83 GiB (11.3%)
 ID-1: /dev/sda vendor: Samsung model: MZ7LN256HCHP-000L7 size: 238.47 GiB
Partition:
 ID-1: / size: 233.24 GiB used: 26.82 GiB (11.5%) fs: ext4 dev: /dev/sda2
Sensors:
 System Temperatures: cpu: 39.5 C mobo: 0.0 C
 Fan Speeds (RPM): cpu: 0
Info:
 Processes: 257 Uptime: 1h 12m Memory: 7.66 GiB used: 2.32 GiB (30.3%)
 Shell: bash inxi: 3.0.38


In conclusion:

Ubuntu 20.04.1 (Focal Fossa LTS)
Gnome 3.36.4
Lenovo ThinkPad T450
Intel HD Graphics 5500 (graphics card)
Mesa Intel HD Graphics 5500 (BDW GT2)
Mesa version: 20.3.0-devel (also happens on Mesa: 20.0.4)
OpenGL version: 4.6

Problem:
2D Displays are not shown and don't work in Repast Simphony

Error Message:
ERROR [AWT-EventQueue-0] 13:46:42,522 repast.simphony.visualizationOGL2D.DisplayOGL2D - Error initializing OGL 2D display. JOGL must be installed and computer must support open gl rendering
javax.media.opengl.GLException: Profile GL2 is not available on null, but: [GLProfile[GLES1/GLES1.hw], GLProfile[GLES2/GLES3.hw], GLProfile[GL2ES1/GLES1.hw], GLProfile[GL4ES3/GL4.hw], GLProfile[GL2ES2/GL4.hw], GLProfile[GL4/GL4.hw], GLProfile[GLES3/GLES3.hw], GLProfile[GL4/GL4.hw], GLProfile[GL3/GL4.hw], GLProfile[GL2GL3/GL4.hw]]

Solution:
Start eclipse from linux terminal by navigating to the folder in which the eclipse executable is located and then using following command (to start eclipse with OpenGL version 3.0):
MESA_GL_VERSION_OVERRIDE=3.0 ./eclipse


By the way the reason it worked fine for my coworker is that he used a VirtualBox on a Windows machine and apparently VirtualBoxes have a cap on the OpenGL version they can use, which means if I remember correctly that the VirtualBox can only use OpenGL versions up to 2.1.
I tested it again with forced OpenGL 2.1:
MESA_GL_VERSION_OVERRIDE=2.1 ./eclipse
and it worked!

Also important might be that I reinstalled my java version, I had openjdk 8 before and uninstalled it to install adopt openjdk 8, after that I also reinstalled Eclipse committers 2019-06 and Repast by following the guide Repast Simphony Update Site on here: https://repast.github.io/download.html
