### ISSUE TITLE
Parameter parcer array out of bounds with batch models that have <2 paramaters 

### ISSUE THREAD

**Issue by maxwenger** [Repast/repast.simphony#41]
When running a model that has fewer than two parameters (in this case, only the random seed) as a batch process, it fails to parse the parameters and exits the model. After adding just a dummy parameter, this issue is resolved and the batch model runs as expected.

Here is the stack trace for the issue, and all parameters in the model at the time of this error.
```
repast.simphony.batch.ssh.LocalSession - ERROR [main] 13:12:24,129 repast.simphony.batch.InstanceRunner - Error while running model
repast.simphony.batch.ssh.LocalSession - java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
repast.simphony.batch.ssh.LocalSession - 	at repast.simphony.batch.parameter.ParameterLineParser.parse(ParameterLineParser.java:55)
repast.simphony.batch.ssh.LocalSession - 	at repast.simphony.batch.InstanceRunner.run(InstanceRunner.java:193)
repast.simphony.batch.ssh.LocalSession - 	at repast.simphony.batch.InstanceRunner.main(InstanceRunner.java:217)
```

![image](https://user-images.githubusercontent.com/3391859/100152191-27d16980-2e57-11eb-868a-f7469f130597.png)

Here is the method from the stack trace that is causing the problems, specifically `params.setValue(param[0].trim(), param[1].trim());`. It looks to me that while parsing, you are trying to grab the 2nd parameter, but in this case, it doesn't exist.
```java
  public Parameters parse(String line) {
    String runNum = line.substring(0, line.indexOf("\t")).trim();
    DefaultParameters params = new DefaultParameters(this.params);
    params.addParameter(BatchConstants.BATCH_RUN_PARAM_NAME, "Batch Run Number", Integer.class , 
        Integer.valueOf(runNum), true);
    
    line = line.substring(line.indexOf("\t") + 1, line.length());
    String[] vals = line.split(",");
    for (String val : vals) {
      String[] param = val.split("\t");
      params.setValue(param[0].trim(), param[1].trim());
    }
    
    return params;
  }

```

Thanks!
Max

**Comment by jozik** [comment]
Thanks for pointing this out. We'll take a look and put in a fix.
