### ISSUE TITLE
repaset simphony 2.4-Initialize model issue

### ISSUE THREAD

**Issue by WangShuangyan** [Repast/repast.simphony#7]
Hi,
I used the flowchart to build the model, and I finished my all flowcharts, then I run the model, but, In the Run Time shows that "Error in invoking the ModelInitializer class", I checked my code again and again, I don't know where is the wrong, please help me! Thank you very much.

**Comment by WangShuangyan** [comment]
There shows that "Caused by: java.lang.NullPointerException", I really don't know where is wrong

**Comment by ncollier** [comment]
There should be a longer error. Can you post that, the full stack trace?

**Comment by WangShuangyan** [comment]
2017/05/31 21:25:57,654: Error while invoking ModelInitializer 'predatorprey.ModelInitializer'
java.lang.reflect.InvocationTargetException
	at predatorprey.ModelInitializer$$FastClassByCGLIB$$43e9363a.invoke(<generated>)
	at net.sf.cglib.reflect.FastMethod.invoke(FastMethod.java:53)
	at repast.simphony.dataLoader.engine.MIContextXMLBuilder.build(MIContextXMLBuilder.java:46)
	at repast.simphony.dataLoader.engine.DataLoaderControllerAction.runInitialize(DataLoaderControllerAction.java:48)
	at repast.simphony.engine.controller.DefaultController$2.visit(DefaultController.java:214)
	at repast.simphony.engine.controller.DefaultController$2.visit(DefaultController.java:1)
	at repast.simphony.util.collections.NaryTree.preOrderTraverals(NaryTree.java:292)
	at repast.simphony.util.collections.NaryTree.preOrderTraverals(NaryTree.java:295)
	at repast.simphony.util.collections.NaryTree.preOrderTraverals(NaryTree.java:295)
	at repast.simphony.util.collections.NaryTree.preOrderTraversal(NaryTree.java:288)
	at repast.simphony.engine.controller.DefaultController.runInitialize(DefaultController.java:212)
	at repast.simphony.engine.controller.DefaultController.runInitialize(DefaultController.java:383)
	at repast.simphony.ui.RSApplication.initSim(RSApplication.java:157)
	at repast.simphony.ui.action.InitRun.actionPerformed(InitRun.java:17)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at repast.simphony.essentials.RepastEssentials.MoveAgent(RepastEssentials.java:921)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:99)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:191)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:227)
	at predatorprey.ModelInitializer.initializeModel(ModelInitializer.groovy:110)
	... 51 more

Thank you

**Comment by ncollier** [comment]
I think you'll get this error if you don't specify the projection correctly. The MoveAgent signature is:

`public static boolean MoveAgent(String projectionPath, Object agent, Number... newAgentLocation) {`

If the projectionPath is incorrect, rather than return the space or grid FindProjection will return null and so you get the NullPointerException.
